Task5
Darina007/bsu-practice-2-cource pull request #3
Opened 2021-03-15 15:27 UTC by Darina007

2021-03-15 22:31 UTC, smiakchilo requested changes
Please remove files not related to Task 5 from the pull request. Then feel free to merge

2021-03-15 22:31 UTC, smiakchilo commented on task5/servlets/CheckServlet.java
> +    protected void doPost(HttpServletRequest request, HttpServletResponse response)
Always use `@Override`  annotation with the methods that - well - override methods from a superclass)

2021-03-15 22:31 UTC, smiakchilo commented on task5/servlets/CheckServlet.java
> +    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
Empty method not needed here

2021-03-15 22:31 UTC, smiakchilo commented on task5/servlets/NameServlet.java
> +        pw.println("<h1 '>Name is { " + name + " } </h1>");
Here's an error in the tag

2021-03-15 22:31 UTC, smiakchilo commented on task5/servlets/StatusServlet.java
> +    protected void doGet(HttpServletRequest request, HttpServletResponse response)
`@Override` missing

2021-03-15 22:31 UTC, smiakchilo commented on task5/servlets/StatusServlet.java
> +    protected void doPost(HttpServletRequest request, HttpServletResponse response)
Redundant method

2021-03-15 22:31 UTC, smiakchilo commented on task5/servlets/Test1ForwardServlet.java
> +    protected void doGet(HttpServletRequest request, HttpServletResponse response)
Same here

2021-03-15 22:31 UTC, smiakchilo commented on task5/servlets/Test1ForwardServlet.java
> +        String path = "/status";
Please take on the notion of constant. Constants are invariable strings, or numbers, etc. that are just "they are as they are". Constants are declared at the beginning of the file like `private static final String PATH = "/status";`

2021-03-15 22:31 UTC, smiakchilo commented on task5/servlets/NameServlet.java
> +        pw.println("<h1 '>Name is { " + name + " } </h1>");
Name length condition check is not there

2021-03-16 13:35 UTC, closed without merging

2021-03-16 13:59 UTC, Darina007 commented
I apologize. It seems I did something wrong and accidentally closed the pull request. I will create a new one and make changes there, and upon your approval, I will delete this one.

2021-03-16 14:19 UTC, smiakchilo commented
Ok)

 

From: Darina Skovysh ***@***.***> 
Sent: Tuesday, March 16, 2021 4:59 PM
To: Darina007/bsu-practice-2-cource ***@***.***>
Cc: Stepan Miakchilo ***@***.***>; Review requested ***@***.***>
Subject: Re: [Darina007/bsu-practice-2-cource] added task 5 (#3)

 

I apologize. It seems I did something wrong and accidentally closed the pull request. I will create a new one and make changes there, and upon your approval, I will delete this one.

—
You are receiving this because your review was requested.
Reply to this email directly, view it on GitHub <https://github.com/Darina007/bsu-practice-2-cource/pull/3#issuecomment-800280645> , or unsubscribe <https://github.com/notifications/unsubscribe-auth/ALUI6RBD3FEOMU23TFR4VVLTD5P4DANCNFSM4ZGYUSEA> .


-- 


CONFIDENTIALITY
NOTICE: This email and files attached to it are 
confidential. If you
are not the intended recipient you are hereby notified 
that using,
copying, distributing or taking any action in reliance on the 
contents of this information is strictly prohibited. If you have
received 
this email in error please notify the sender and delete this
email.